# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Mining
    url: https://zealous-pebble-0690ccb1e.azurestaticapps.net/
  - name: Mining Site
    url: https://mining-server.azurewebsites.net/
  - name: Mernday
    url: https://mernday.tech/
  - name: Mernday (www)
    url: https://www.mernday.tech/
  - name: one 
    url: https://lyrical-patch.surge.sh/
  - name: two
    url: https://new-age.surge.sh/
  - name: three
    url: https://shaggy-cherries.surge.sh
  - name: four
    url: https://unwritten-flame.surge.sh
  - name: five
    url: https://willing-level.surge.sh
  - name: six
    url: https://yellow-disk-0217.bss.design/
  - name: seven
    url: https://mute-butterfly-4357.bss.design/
  - name: eight
    url: https://attractive-tank.surge.sh
  - name: nine
    url: https://combative-weather.surge.sh/
  - name: ten
    url:  https://knotty-person.surge.sh/   
  - name: eleven
    url: http://restaurant-4e27e.web.app/
  - name: twelve
    url: http://malik-shoestore.surge.sh/  
  - name: thirteen
    url: https://malik-quiz-app.surge.sh/
    
    
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
